# Generated by Django 3.1.6 on 2021-02-25 06:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin1', '0002_auto_20210215_2125'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer_name', models.CharField(max_length=20)),
                ('discount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('category', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='admin1.category')),
            ],
        ),
    ]
