# Generated by Django 3.1.6 on 2021-02-25 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin1', '0003_offer'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='start',
            field=models.BooleanField(default=False),
        ),
    ]
