# Generated by Django 3.1.6 on 2021-02-25 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin1', '0005_coupen'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupen',
            name='coupen_name',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='coupen',
            name='code',
            field=models.CharField(max_length=50),
        ),
    ]
