# Generated by Django 3.1.6 on 2021-02-25 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin1', '0006_auto_20210225_1833'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupen',
            name='live',
            field=models.BooleanField(default=False),
        ),
    ]
