# Generated by Django 3.1.6 on 2021-02-26 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin1', '0007_coupen_live'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roomoverview',
            name='pic1',
        ),
        migrations.RemoveField(
            model_name='roomoverview',
            name='pic2',
        ),
        migrations.RemoveField(
            model_name='roomoverview',
            name='pic3',
        ),
        migrations.RemoveField(
            model_name='roomoverview',
            name='pic4',
        ),
        migrations.RemoveField(
            model_name='roomoverview',
            name='pic5',
        ),
        migrations.RemoveField(
            model_name='roomoverview',
            name='pic6',
        ),
    ]
