# Generated by Django 3.1.6 on 2021-02-26 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin1', '0009_roompic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roompic',
            name='pic',
            field=models.ImageField(null=True, upload_to='pics'),
        ),
    ]
