# Generated by Django 3.1.6 on 2021-02-19 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reception', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='receptionbook',
            name='contact',
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='receptionbook',
            name='guest_name',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
