# Generated by Django 3.1.6 on 2021-02-24 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reception', '0002_auto_20210219_1135'),
    ]

    operations = [
        migrations.AddField(
            model_name='receptionbook',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True),
        ),
    ]
