# Generated by Django 3.1.6 on 2021-02-18 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_bookroom'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookroom',
            name='checked_out',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
