# Generated by Django 3.1.6 on 2021-02-23 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_bookroom_checked_out'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookroom',
            name='price',
            field=models.IntegerField(null=True),
        ),
    ]
