# Generated by Django 3.1.6 on 2021-02-24 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_bookroom_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookroom',
            name='block',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
