# Generated by Django 3.1.6 on 2021-02-24 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_bookroom_block'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookroom',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True),
        ),
    ]
