# Generated by Django 3.1.6 on 2021-02-24 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='check',
            field=models.BooleanField(default=False),
        ),
    ]
