# Generated by Django 3.1.6 on 2021-02-24 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_review_check'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='done',
            field=models.BooleanField(default=False),
        ),
    ]
