# Generated by Django 3.1.6 on 2021-02-24 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_review_done'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='user',
        ),
    ]
