# Generated by Django 3.1.6 on 2021-02-24 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_remove_review_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='check',
        ),
    ]
