# Generated by Django 3.1.6 on 2021-02-24 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_remove_review_check'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='done',
        ),
    ]
