# Generated by Django 3.1.6 on 2021-02-24 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin1', '0002_auto_20210215_2125'),
        ('user', '0013_remove_review_done'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='admin1.roomoverview'),
        ),
    ]
