from django.urls import path
from . import views

urlpatterns = [
    path('',views.login, name='login'),
    path('adminhome/',views.adminhome,name='adminhome'),
    path('viewuser/',views.viewuser,name='viewuser'),
    path('edituser/<int:id>',views.edituser,name='edituser'),
    path('adduser/',views.adduser,name='adduser'),
    path('deleteuser/<int:id>',views.deleteuser,name='deleteuser'),
    path('blockuser/<int:id>',views.blockuser,name='blockuser'),
    path('viewreceptionist/',views.viewreceptionist,name='viewreceptionist'),
    path('editreceptionist/<int:id>',views.editreceptionist,name='editreceptionist'),
    path('addreceptionist/',views.addreceptionist,name='addreceptionist'),
    path('deletereceptionist/<int:id>',views.deletereceptionist,name='deletereceptionist'),
    path('viewrooms/',views.viewrooms,name='viewrooms'),
    path('addoverview/', views.add_over_view, name='addoverview'),
    path('addroompic/<int:id>',views.add_room_pic,name='addroompic'),
    path('viewroompic/<int:id>',views.view_room_pic,name='viewroompic'), 
    path('removepic/<int:id>',views.remove_pic,name='removepic'),
    path('editoverview/<int:id>',views.edit_over_view, name = 'editoverview'),
    path('deleteoverview/<int:id>', views.delete_over_view, name='deleteoverview'),
    path('roomstatus/',views.roomstatus, name='roomstatus'),
    path('category/',views.categories,name='categories'),
    path('addcategory/',views.addcategory,name = 'addcategory'),
    path('deletecategory/<int:id>',views.deletecategory,name= 'deletecategory'),
    path('amenities/',views.amenities,name='amenities1'),
    path('addamenities/',views.addamenities,name='addamenities'),
    path('deleteamenities/<int:id>',views.deleteamenities,name='deleteamenities'),
    path('bookings/',views.bookings,name='viewbooking'),
    path('receptionbook/',views.reception_book,name='receptionbook'),
    path('blockbook/<int:id>',views.blockbook,name = 'blockbook'),
    path('deletebook/<int:id>',views.deletebook,name = 'deletebook'),
    path('reports/',views.reports, name='reports'),
    path('datereport/',views.datereport, name='datereport'),
    path('viewoffer/',views.view_offer,name='viewoffer'),
    path('addoffer/',views.add_offer,name='addoffer'),
    path('deleteoffer/<int:id>',views.delete_offer,name = 'deleteoffer'),
    path('addcoupen/',views.add_coupen,name='addcoupen'),
    path('deletecoupen/',views.delete_coupen,name='deletecoupen'),
    path('viewreview/',views.view_reviews,name='reviews'),
    path('logout/',views.logout,name='logout')
]